menu:
  home: /
  archives: /archives
  books: https://denley_say.justtodo.com/
  about: /about

submenu:

menu_icon:
  home: home
  archives: archive
  Node.js: book
  books: book
  about: user
  rss: rss
  customization: question-circle

widgets:
- search
- category
- tagcloud
- archive
# - tag
# - calendar
# - weixin
- links
# - weibo

excerpt_link: 阅读原文
comment_link: 所有评论

# header头像
avatar: /assets/images/avator.jpeg
# header右侧图片展示
ad:

# 评论提供可以选择 duoshuo 或者 wumii，无需评论，此处不填就行。 // duoshuo已经废除
comment_provider: gitment

# 百度分享
baidu_share: true

# 请到after_footer.ejs中替换百度统计代码
baidu_tongji: true

# 微博: height小挂件高度；url替换成自己的微博挂件地址，同步修改url中height的值
weibo:
  height: 600
  url: http://widget.weibo.com/weiboshow/index.php?language=&width=0&height=600&fansRow=1&ptype=1&speed=0&skin=1&isTitle=0&noborder=0&isWeibo=1&isFans=0&uid=1934606495&verifier=a6769878&dpc=1

# Calendar
calendar:
  language: zh-CN
  single: true
  root: /calendar/

# weixin
weixin:
  qrcode: /assets/images/weixin.jpeg

# links
links:

# farbox
fancybox: true

# Gitment
# Introduction: https://imsun.net/posts/gitment-introduction/
gitment:
  enable: true
  mint: true # RECOMMEND, A mint on Gitment, to support count, language and proxy_gateway
  count: true # Show comments count in post meta area
  lazy: false # Comments lazy loading with a button
  cleanly: false # Hide 'Powered by ...' on footer, and more
  language: # Force language, or auto switch by theme
  github_user: 'denleysay' # MUST HAVE, Your Github Username
  github_repo: 'denleysay.github.io' # MUST HAVE, The name of the repo you use to store Gitment comments
  client_id: '63f076a5b81ab1299f4c' # MUST HAVE, Github client id for the Gitment
  client_secret: 'd1f252924d55c0ef18987c4fcd0928b42bf19427' # EITHER this or proxy_gateway, Github access secret token for the Gitment
  proxy_gateway: # Address of api proxy, See: https://github.com/aimingoo/intersect
  redirect_protocol: # Protocol of redirect_uri with force_redirect_protocol when mint enabled
